apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: instantdeploy-postgres-pvc
  namespace: instantdeploy
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
