apiVersion: v1
kind: Secret
metadata:
  name: instantdeploy-postgres-secret
  namespace: instantdeploy
type: Opaque
stringData:
  POSTGRES_DB: instantdeploy
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
